version: '3.8'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
      args:
        USER_ID: '${WWWUSER:-1000}'
        GROUP_ID: '${WWWGROUP:-1000}'
        USER: '${USER:-whoami}'
    container_name: taskify-app
    restart: always
    working_dir: /var/www/
    environment:
      - TZ=Africa/Lagos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9003:9003"
    volumes:
      - ../src/:/var/www
  nginx:
    image: nginx:1.25.4-alpine
    container_name: taskify-server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src/:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: taskify-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  mailhog:
    container_name: taskify-mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: "none"
    ports:
      - "8025:8025"
      - "1025:1025"
